INSERT INTO nacionalidades (nacionalidad) VALUES
('Afgana'),
('Albanesa'),
('Alemana'),
('Andorrana'),
('Angoleña'),
('Argentina'),
('Australiana'),
('Belga'),
('Boliviana'),
('Brasileña'),
('Canadiense'),
('Chilena'),
('China'),
('Colombiana'),
('Costarricense'),
('Cubana'),
('Ecuatoriana'),
('Egipcia'),
('Española'),
('Estadounidense'),
('Filipina'),
('Francesa'),
('Guatemalteca'),
('Hondureña'),
('India'),
('Italiana'),
('Japonesa'),
('Mexicana'),
('Panameña'),
('Paraguaya'),
('Peruana'),
('Portuguesa'),
('Salvadoreña'),
('Suiza'),
('Uruguaya'),
('Venezolana');



INSERT INTO departamentos (departamento, idnacionalidad) VALUES
('Amazonas', 31),
('Áncash', 31),
('Apurímac', 31),
('Arequipa', 31),
('Ayacucho', 31),
('Cajamarca', 31),
('Callao', 31),
('Cusco', 31),
('Huancavelica', 31),
('Huánuco', 31),
('Ica', 31),
('Junín', 31),
('La Libertad', 31),
('Lambayeque', 31),
('Lima', 31),
('Loreto', 31),
('Madre de Dios', 31),
('Moquegua', 31),
('Pasco', 31),
('Piura', 31),
('Puno', 31),
('San Martín', 31),
('Tacna', 31),
('Tumbes', 31),
('Ucayali', 31);



INSERT INTO provincias (iddepartamento, provincia) VALUES 
(1, 'Bagua'),
(1, 'Bongará'),
(1, 'Chachapoyas'),
(1, 'Condorcanqui'),
(1, 'Luya'),
(1, 'Rodríguez de Mendoza'),
(1, 'Utcubamba'),

(2, 'Aija'),
(2, 'Antonio Raymondi'),
(2, 'Asunción'),
(2, 'Bolognesi'),
(2, 'Carhuaz'),
(2, 'Carlos Fermín Fitzcarrald'),
(2, 'Casma'),
(2, 'Corongo'),
(2, 'Huaraz'),
(2, 'Huari'),
(2, 'Huarmey'),
(2, 'Mariscal Luzuriaga'),
(2, 'Ocros'),
(2, 'Pallasca'),
(2, 'Pomabamba'),
(2, 'Recuay'),
(2, 'Santa'),
(2, 'Sihuas'),
(2, 'Yungay'),


(3, 'Abancay'),
(3, 'Andahuaylas'),
(3, 'Antabamba'),
(3, 'Aymaraes'),
(3, 'Cotabambas'),
(3, 'Chincheros'),
(3, 'Grau'),

(4, 'Arequipa'),
(4, 'Camaná'),
(4, 'Caravelí'),
(4, 'Castilla'),
(4, 'Caylloma'),
(4, 'Condesuyos'),
(4, 'Islay'),
(4, 'La Unión'),

(5, 'Cangallo'),
(5, 'Huamanga'),
(5, 'Huanca Sancos'),
(5, 'Huanta'),
(5, 'La Mar'),
(5, 'Lucanas'),
(5, 'Parinacochas'),
(5, 'Páucar del Sara Sara'),
(5, 'Sucre'),
(5, 'Víctor Fajardo'),
(5, 'Vilcas Huamán'),

(6, 'Cajabamba'),
(6, 'Cajamarca'),
(6, 'Celendín'),
(6, 'Chota'),
(6, 'Contumazá'),
(6, 'Cutervo'),
(6, 'Hualgayoc'),
(6, 'Jaén'),
(6, 'San Ignacio'),
(6, 'San Marcos'),
(6, 'San Miguel'),
(6, 'San Pablo'),
(6, 'Santa Cruz'),

(7, 'Callao'),

(8, 'Acomayo'),
(8, 'Anta'),
(8, 'Calca'),
(8, 'Canas'),
(8, 'Canchis'),
(8, 'Chumbivilcas'),
(8, 'Cusco'),
(8, 'Espinar'),
(8, 'La Convención'),
(8, 'Paruro'),
(8, 'Paucartambo'),
(8, 'Quispicanchi'),
(8, 'Urubamba'),

(9, 'Acobamba'),
(9, 'Angaraes'),
(9, 'Castrovirreyna'),
(9, 'Churcampa'),
(9, 'Huancavelica'),
(9, 'Huaytará'),
(9, 'Tayacaja'),

(10, 'Ambo'),
(10, 'Dos de Mayo'),
(10, 'Huacaybamba'),
(10, 'Huamalíes'),
(10, 'Huánuco'),
(10, 'Lauricocha'),
(10, 'Leoncio Prado'),
(10, 'Marañón'),
(10, 'Pachitea'),
(10, 'Puerto Inca'),
(10, 'Yarowilca'),

(11, 'Chincha'),
(11, 'Ica'),
(11, 'Nazca'),
(11, 'Palpa'),
(11, 'Pisco'),

(12, 'Chanchamayo'),
(12, 'Chupaca'),
(12, 'Concepción'),
(12, 'Huancayo'),
(12, 'Jauja'),
(12, 'Junín'),
(12, 'Satipo'),
(12, 'Tarma'),
(12, 'Yauli'),

(13, 'Ascope'),
(13, 'Bolívar'),
(13, 'Chepén'),
(13, 'Gran Chimú'),
(13, 'Julcán'),
(13, 'Otuzco'),
(13, 'Pacasmayo'),
(13, 'Pataz'),
(13, 'Sánchez Carrión'),
(13, 'Santiago de Chuco'),
(13, 'Trujillo'),
(13, 'Virú'),

(14, 'Chiclayo'),
(14, 'Ferreñafe'),
(14, 'Lambayeque'),

(15, 'Barranca'),
(15, 'Cajatambo'),
(15, 'Canta'),
(15, 'Cañete'),
(15, 'Huaral'),
(15, 'Huarochirí'),
(15, 'Huaura'),
(15, 'Lima'),
(15, 'Oyón'),
(15, 'Yauyos'),

(16, 'Alto Amazonas'),
(16, 'Datem del Marañón'),
(16, 'Loreto'),
(16, 'Mariscal Ramón Castilla'),
(16, 'Maynas'),
(16, 'Putumayo'),
(16, 'Requena'),
(16, 'Ucayali'),

(17, 'Manu'),
(17, 'Tahuamanu'),
(17, 'Tambopata'),

(18, 'General Sánchez Cerro'),
(18, 'Ilo'),
(18, 'Mariscal Nieto'),

(19, 'Daniel Alcides Carrión'),
(19, 'Oxapampa'),
(19, 'Pasco'),

(20, 'Ayabaca'),
(20, 'Huancabamba'),
(20, 'Morropón'),
(20, 'Paita'),
(20, 'Piura'),
(20, 'Sechura'),
(20, 'Sullana'),
(20, 'Talara'),

(21, 'Azángaro'),
(21, 'Carabaya'),
(21, 'Chucuito'),
(21, 'El Collao'),
(21, 'Huancané'),
(21, 'Lampa'),
(21, 'Melgar'),
(21, 'Moho'),
(21, 'Puno'),
(21, 'San Antonio de Putina'),
(21, 'San Román'),
(21, 'Sandia'),
(21, 'Yunguyo'),

(22, 'Bellavista'),
(22, 'El Dorado'),
(22, 'Huallaga'),
(22, 'Lamas'),
(22, 'Mariscal Cáceres'),
(22, 'Moyobamba'),
(22, 'Picota'),
(22, 'Rioja'),
(22, 'San Martín'),
(22, 'Tocache'),

(23, 'Candarave'),
(23, 'Jorge Basadre'),
(23, 'Tacna'),
(23, 'Tarata'),

(24, 'Contralmirante Villar'),
(24, 'Tumbes'),
(24, 'Zarumilla'),

(25, 'Atalaya'),
(25, 'Coronel Portillo'),
(25, 'Padre Abad'),
(25, 'Purús');


INSERT INTO distritos (idprovincia, distrito) VALUES 
-- BAGUA
-- bagua
(1, 'Bagua'),
(1, 'Aramango'),
(1, 'Copallín'),
(1, 'El Parco'),
(1, 'Imaza'),
(1, 'La Peca'),
-- bongara
(2, 'Jumbilla'),
(2, 'Chisquilla'),
(2, 'Churuja'),
(2, 'Corosha'),
(2, 'Cuispes'),
(2, 'Florida'),
(2, 'Jazán'),
(2, 'Recta'),
(2, 'San Carlos'),
(2, 'Shipasbamba'),
(2, 'Valera'),
(2, 'Yambrasbamba'),
-- chachapoyas
(3, 'Chachapoyas'),
(3, 'Asunción'),
(3, 'Balsas'),
(3, 'Cheto'),
(3, 'Chiliquin'),
(3, 'Chuquibamba'),
(3, 'Granada'),
(3, 'Huancas'),
(3, 'La Jalca'),
(3, 'Leimebamba'),
(3, 'Levanto'),
(3, 'Magdalena'),
(3, 'Mariscal Castilla'),
(3, 'Molinopampa'),
(3, 'Montevideo'),
(3, 'Olleros'),
(3, 'Quinjalca'),
(3, 'San Francisco de Daguas'),
(3, 'San Isidro de Maino'),
(3, 'Soloco'),
(3, 'Sonche'),

(4, 'Santa María de Nieva'),
(4, 'El Cenepa'),
(4, 'Río Santiago'),

(5, 'Lamud'),
(5, 'Camporredondo'),
(5, 'Cocabamba'),
(5, 'Colcamar'),
(5, 'Conila'),
(5, 'Inguilpata'),
(5, 'Longuita'),
(5, 'Lonya Chico'),
(5, 'Luya'),
(5, 'Luya Viejo'),
(5, 'María'),
(5, 'Ocalli'),
(5, 'Ocumal'),
(5, 'Pisuquía'),
(5, 'Providencia'),
(5, 'San Cristóbal'),
(5, 'San Francisco del Yeso'),
(5, 'San Jerónimo'),
(5, 'San Juan de Lopecancha'),
(5, 'Santa Catalina'),
(5, 'Santo Tomás'),
(5, 'Tingo'),
(5, 'Trita'),

(6, 'San Nicolás'),
(6, 'Chirimoto'),
(6, 'Cochamal'),
(6, 'Huambo'),
(6, 'Limabamba'),
(6, 'Longar'),
(6, 'Mariscal Benavides'),
(6, 'Milpuc'),
(6, 'Omia'),
(6, 'Santa Rosa'),
(6, 'Totora'),
(6, 'Vista Alegre'),

(7, 'Bagua Grande'),
(7, 'Cajaruro'),
(7, 'Cumba'),
(7, 'El Milagro'),
(7, 'Jamalca'),
(7, 'Lonya Grande'),
(7, 'Yamón'),

-- 

(8, 'Aija'),
(8, 'Coris'),
(8, 'Huacllan'),
(8, 'La Merced'),
(8, 'Succha'),
(9, 'Llamellín'),
(9, 'Aczo'),
(9, 'Chaccho'),
(9, 'Chingas'),
(9, 'Mirgas'),
(9, 'San Juan de Rontoy'),
(10, 'Chacas'),
(10, 'Acochaca'),
(11, 'Chiquián'),
(11, 'Abelardo Pardo Lezameta'),
(11, 'Antonio Raymondi'),
(11, 'Aquia'),
(11, 'Cajacay'),
(11, 'Canis'),
(11, 'Colquioc'),
(11, 'Huallanca'),
(11, 'Huasta'),
(11, 'Huayllacayan'),
(11, 'La Primavera'),
(11, 'Mangas'),
(11, 'Pacllon'),
(11, 'San Miguel de Corpanqui'),
(11, 'Ticllos'),
(12, 'Carhuaz'),
(12, 'Acopampa'),
(12, 'Amashca'),
(12, 'Anta'),
(12, 'Ataquero'),
(12, 'Marcara'),
(12, 'Pariahuanca'),
(12, 'San Miguel de Aco'),
(12, 'Shilla'),
(12, 'Tinco'),
(12, 'Yungar'),
(13, 'San Luis'),
(13, 'San Nicolás'),
(13, 'Yauya'),
(14, 'Casma'),
(14, 'Buena Vista Alta'),
(14, 'Comandante Noel'),
(14, 'Yautan'),
(15, 'Corongo'),
(15, 'Aco'),
(15, 'Bambas'),
(15, 'Cusca'),
(15, 'La Pampa'),
(15, 'Yanac'),
(15, 'Yupan'),
(16, 'Huaraz'),
(16, 'Cochabamba'),
(16, 'Colcabamba'),
(16, 'Huanchay'),
(16, 'Independencia'),
(16, 'Jangas'),
(16, 'La Libertad'),
(16, 'Olleros'),
(16, 'Pampas'),
(16, 'Pariacoto'),
(16, 'Pira'),
(16, 'Tarica'),
(17, 'Huari'),
(17, 'Anra'),
(17, 'Cajay'),
(17, 'Chavin de Huantar'),
(17, 'Huacachi'),
(17, 'Huacchis'),
(17, 'Huachis'),
(17, 'Huantar'),
(17, 'Masin'),
(17, 'Paucas'),
(17, 'Ponto'),
(17, 'Rahuapampa'),
(17, 'Rapayan'),
(17, 'San Marcos'),
(17, 'San Pedro de Chana'),
(17, 'Uco'),
(18, 'Huarmey'),
(18, 'Cochapeti'),
(18, 'Culebras'),
(18, 'Huayan'),
(18, 'Malvas'),
(19, 'Piscobamba'),
(19, 'Casca'),
(19, 'Eleazar Guzmán Barrón'),
(19, 'Fidel Olivas Escudero'),
(19, 'Llama'),
(19, 'Llumpa'),
(19, 'Lucma'),
(19, 'Musga'),
(20, 'Ocros'),
(20, 'Acas'),
(20, 'Cajamarquilla'),
(20, 'Carhuapampa'),
(20, 'Cochas'),
(20, 'Congas'),
(20, 'Llipa'),
(20, 'San Cristóbal de Rajan'),
(20, 'San Pedro'),
(20, 'Santiago de Chilcas'),
(21, 'Cabana'),
(21, 'Bolognesi'),
(21, 'Conchucos'),
(21, 'Huacaschuque'),
(21, 'Huandoval'),
(21, 'Lacabamba'),
(21, 'Llapo'),
(21, 'Pallasca'),
(21, 'Pampas'),
(21, 'Santa Rosa'),
(21, 'Tauca'),
(22, 'Pomabamba'),
(22, 'Huayllan'),
(22, 'Parobamba'),
(22, 'Quinuabamba'),
(23, 'Recuay'),
(23, 'Catac'),
(23, 'Cotaparaco'),
(23, 'Huayllapampa'),
(23, 'Llacllin'),
(23, 'Marca'),
(23, 'Pampas Chico'),
(23, 'Pararin'),
(23, 'Tapacocha'),
(23, 'Ticapampa'),
(24, 'Chimbote'),
(24, 'Cáceres del Perú'),
(24, 'Coishco'),
(24, 'Macate'),
(24, 'Moro'),
(24, 'Nepeña'),
(24, 'Samanco'),
(24, 'Santa'),
(24, 'Nuevo Chimbote'),
(25, 'Sihuas'),
(25, 'Acobamba'),
(25, 'Alfonso Ugarte'),
(25, 'Cashapampa'),
(25, 'Chingalpo'),
(25, 'Huayllabamba'),
(25, 'Quiches'),
(25, 'Ragash'),
(25, 'San Juan'),
(25, 'Sicsibamba'),
(26, 'Yungay'),
(26, 'Cascapara'),
(26, 'Mancos'),
(26, 'Matacoto'),
(26, 'Quillo'),
(26, 'Ranrahirca'),
(26, 'Shupluy'),
(26, 'Yanama'),

-- Provincia: Abancay
(27, 'Abancay'),
(27, 'Chacoche'),
(27, 'Circa'),
(27, 'Curahuasi'),
(27, 'Huanipaca'),
(27, 'Lambrama'),
(27, 'Pichirhua'),
(27, 'San Pedro de Cachora'),
(27, 'Tamburco'),

-- Provincia: Andahuaylas
(28, 'Andahuaylas'),
(28, 'Andarapa'),
(28, 'Chiara'),
(28, 'Huancarama'),
(28, 'Huancaray'),
(28, 'Huayana'),
(28, 'José María Arguedas'),
(28, 'Kaquiabamba'),
(28, 'Kishuara'),
(28, 'Pacobamba'),
(28, 'Pacucha'),
(28, 'Pampachiri'),
(28, 'Pomacocha'),
(28, 'San Antonio de Cachi'),
(28, 'San Jerónimo'),
(28, 'San Miguel de Chaccrampa'),
(28, 'Santa María de Chicmo'),
(28, 'Talavera'),
(28, 'Tumay Huaraca'),
(28, 'Turpo'),

-- Provincia: Antabamba
(29, 'Antabamba'),
(29, 'El Oro'),
(29, 'Huaquirca'),
(29, 'Juan Espinoza Medrano'),
(29, 'Oropesa'),
(29, 'Pachaconas'),
(29, 'Sabaino'),

-- Provincia: Aymaraes
(30, 'Chalhuanca'),
(30, 'Capaya'),
(30, 'Caraybamba'),
(30, 'Chapimarca'),
(30, 'Colcabamba'),
(30, 'Cotaruse'),
(30, 'Ihuayllo'),
(30, 'Justo Apu Sahuaraura'),
(30, 'Lucre'),
(30, 'Pocohuanca'),
(30, 'San Juan de Chacña'),
(30, 'Sañayca'),
(30, 'Soraya'),
(30, 'Tapairihua'),
(30, 'Tintay'),
(30, 'Toraya'),
(30, 'Yanaca'),

-- Provincia: Cotabambas
(31, 'Tambobamba'),
(31, 'Cotabambas'),
(31, 'Coyllurqui'),
(31, 'Haquira'),
(31, 'Mara'),
(31, 'Challhuahuacho'),

-- Provincia: Chincheros
(32, 'Chincheros'),
(32, 'Anco-Huallo'),
(32, 'Cocharcas'),
(32, 'Huaccana'),
(32, 'Ocobamba'),
(32, 'Ongoy'),
(32, 'Uranmarca'),
(32, 'Ranracancha'),
(32, 'Rocchacc'),

-- Provincia: Grau
(33, 'Chuquibambilla'),
(33, 'Curpahuasi'),
(33, 'Gamarra'),
(33, 'Huayllati'),
(33, 'Mamara'),
(33, 'Micaela Bastidas'),
(33, 'Pataypampa'),
(33, 'Progreso'),
(33, 'San Antonio'),
(33, 'Santa Rosa'),
(33, 'Turpay'),
(33, 'Vilcabamba'),
(33, 'Virundo'),
(33, 'Curasco');

-- Provincia: Arequipa
(34, 'Arequipa'),
(34, 'Alto Selva Alegre'),
(34, 'Cayma'),
(34, 'Cerro Colorado'),
(34, 'Characato'),
(34, 'Chiguata'),
(34, 'Jacobo Hunter'),
(34, 'La Joya'),
(34, 'Mariano Melgar'),
(34, 'Miraflores'),
(34, 'Mollebaya'),
(34, 'Paucarpata'),
(34, 'Pocsi'),
(34, 'Polobaya'),
(34, 'Quequeña'),
(34, 'Sabandía'),
(34, 'Sachaca'),
(34, 'San Juan de Siguas'),
(34, 'San Juan de Tarucani'),
(34, 'Santa Isabel de Siguas'),
(34, 'Santa Rita de Siguas'),
(34, 'Socabaya'),
(34, 'Tiabaya'),
(34, 'Uchumayo'),
(34, 'Vitor'),
(34, 'Yanahuara'),
(34, 'Yarabamba'),
(34, 'Yura'),

-- Provincia: Camaná
(35, 'Camaná'),
(35, 'José María Quimper'),
(35, 'Mariano Nicolás Valcárcel'),
(35, 'Mariscal Cáceres'),
(35, 'Nicolás de Piérola'),
(35, 'Ocoña'),
(35, 'Quilca'),
(35, 'Samuel Pastor'),

-- Provincia: Caravelí
(36, 'Caravelí'),
(36, 'Acarí'),
(36, 'Atico'),
(36, 'Atiquipa'),
(36, 'Bella Unión'),
(36, 'Cahuacho'),
(36, 'Chala'),
(36, 'Chaparra'),
(36, 'Huanuhuanu'),
(36, 'Jaqui'),
(36, 'Lomas'),
(36, 'Quicacha'),
(36, 'Yauca'),

-- Provincia: Castilla
(37, 'Aplao'),
(37, 'Andagua'),
(37, 'Ayo'),
(37, 'Chachas'),
(37, 'Chilcaymarca'),
(37, 'Choco'),
(37, 'Huancarqui'),
(37, 'Machaguay'),
(37, 'Orcopampa'),
(37, 'Pampacolca'),
(37, 'Tipán'),
(37, 'Uñón'),
(37, 'Uraca'),
(37, 'Viraco'),

-- Provincia: Caylloma
(38, 'Chivay'),
(38, 'Achoma'),
(38, 'Cabanaconde'),
(38, 'Callalli'),
(38, 'Caylloma'),
(38, 'Coporaque'),
(38, 'Huambo'),
(38, 'Huanca'),
(38, 'Ichupampa'),
(38, 'Lari'),
(38, 'Lluta'),
(38, 'Maca'),
(38, 'Madrigal'),
(38, 'San Antonio de Chuca'),
(38, 'Sibayo'),
(38, 'Tapay'),
(38, 'Tisco'),
(38, 'Tuti'),
(38, 'Yanque'),

-- Provincia: Condesuyos
(39, 'Chuquibamba'),
(39, 'Andaray'),
(39, 'Cayarani'),
(39, 'Chichas'),
(39, 'Iray'),
(39, 'Río Grande'),
(39, 'Salamanca'),
(39, 'Yanaquihua'),

-- Provincia: Islay
(40, 'Mollendo'),
(40, 'Cocachacra'),
(40, 'Dean Valdivia'),
(40, 'Islay'),
(40, 'Mejía'),
(40, 'Punta de Bombón'),

-- Provincia: La Unión
(41, 'Cotahuasi'),
(41, 'Alca'),
(41, 'Charcana'),
(41, 'Huaynacotas'),
(41, 'Pampamarca'),
(41, 'Puyca'),
(41, 'Quechualla'),
(41, 'Sayla'),
(41, 'Tauría'),
(41, 'Tomepampa'),
(41, 'Toro');

-- Provincia: Cangallo
(42, 'Cangallo'),
(42, 'Chuschi'),
(42, 'Los Morochucos'),
(42, 'María Parado de Bellido'),
(42, 'Paras'),
(42, 'Totos'),

-- Provincia: Huamanga
(43, 'Ayacucho'),
(43, 'Acocro'),
(43, 'Acos Vinchos'),
(43, 'Carmen Alto'),
(43, 'Chiara'),
(43, 'Jesús Nazareno'),
(43, 'Ocros'),
(43, 'Pacaycasa'),
(43, 'Quinua'),
(43, 'San José de Ticllas'),
(43, 'San Juan Bautista'),
(43, 'Santiago de Pischa'),
(43, 'Socos'),
(43, 'Tambillo'),
(43, 'Vinchos'),
(43, 'Andrés Avelino Cáceres Dorregaray'),

-- Provincia: Huanca Sancos
(44, 'Sancos'),
(44, 'Carapo'),
(44, 'Sacsamarca'),
(44, 'Santiago de Lucanamarca'),

-- Provincia: Huanta
(45, 'Huanta'),
(45, 'Ayahuanco'),
(45, 'Huamanguilla'),
(45, 'Iguain'),
(45, 'Luricocha'),
(45, 'Santillana'),
(45, 'Sivia'),
(45, 'Llochegua'),
(45, 'Canayre'),
(45, 'Uchuraccay'),
(45, 'Pucacolpa'),

-- Provincia: La Mar
(46, 'San Miguel'),
(46, 'Anco'),
(46, 'Ayna'),
(46, 'Chilcas'),
(46, 'Chungui'),
(46, 'Luis Carranza'),
(46, 'Santa Rosa'),
(46, 'Tambo'),
(46, 'Samugari'),
(46, 'Anchihuay'),

-- Provincia: Lucanas
(47, 'Puquio'),
(47, 'Aucara'),
(47, 'Cabana'),
(47, 'Carmen Salcedo'),
(47, 'Chaviña'),
(47, 'Chipao'),
(47, 'Huac-Huas'),
(47, 'Laramate'),
(47, 'Leoncio Prado'),
(47, 'Llauta'),
(47, 'Lucanas'),
(47, 'Ocaña'),
(47, 'Otoca'),
(47, 'Saisa'),
(47, 'San Cristóbal'),
(47, 'San Juan'),
(47, 'San Pedro'),
(47, 'San Pedro de Palco'),
(47, 'Sancos'),
(47, 'Santa Ana de Huaycahuacho'),

-- Provincia: Parinacochas
(48, 'Coracora'),
(48, 'Chumpi'),
(48, 'Coronel Castañeda'),
(48, 'Pacapausa'),
(48, 'Pullo'),
(48, 'Puyusca'),
(48, 'San Francisco de Ravacayco'),
(48, 'Upahuacho'),

-- Provincia: Páucar del Sara Sara
(49, 'Pausa'),
(49, 'Colta'),
(49, 'Corculla'),
(49, 'Lampa'),
(49, 'Marcabamba'),
(49, 'Oyolo'),
(49, 'Pararca'),
(49, 'San Javier de Alpabamba'),
(49, 'San José de Ushua'),
(49, 'Sara Sara'),

-- Provincia: Sucre
(50, 'Querobamba'),
(50, 'Belén'),
(50, 'Chalcos'),
(50, 'San Pedro de Larcay'),
(50, 'San Salvador de Quije'),
(50, 'Santiago de Paucaray'),
(50, 'Soras'),

-- Provincia: Víctor Fajardo
(51, 'Huancapi'),
(51, 'Alcamenca'),
(51, 'Apongo'),
(51, 'Asquipata'),
(51, 'Canaria'),
(51, 'Cayara'),
(51, 'Colca'),
(51, 'Huamanquiquia'),
(51, 'Huancaraylla'),
(51, 'Huaya'),
(51, 'Sarhua'),
(51, 'Vilcanchos'),

-- Provincia: Vilcas Huamán
(52, 'Vilcas Huamán'),
(52, 'Accomarca'),
(52, 'Carhuanca'),
(52, 'Concepción'),
(52, 'Huambalpa'),
(52, 'Independencia'),
(52, 'Saurama'),
(52, 'Vischongo'),

-- Provincia: Cajabamba
(53, 'Cajabamba'),
(53, 'Cachachi'),
(53, 'Condebamba'),
(53, 'Sitacocha'),

-- Provincia: Cajamarca
(54, 'Cajamarca'),
(54, 'Asunción'),
(54, 'Chetilla'),
(54, 'Cospán'),
(54, 'Jesús'),
(54, 'Los Baños del Inca'),
(54, 'Magdalena'),
(54, 'Matara'),
(54, 'Namora'),
(54, 'San Juan'),

-- Provincia: Celendín
(55, 'Celendín'),
(55, 'Chumuch'),
(55, 'Cortegana'),
(55, 'Huasmin'),
(55, 'Jorge Chávez'),
(55, 'José Gálvez'),
(55, 'Miguel Iglesias'),
(55, 'Oxamarca'),
(55, 'Sorochuco'),
(55, 'Sucre'),
(55, 'Utco'),
(55, 'La Libertad de Pallán'),

-- Provincia: Chota
(56, 'Chota'),
(56, 'Anguía'),
(56, 'Chadin'),
(56, 'Chiguirip'),
(56, 'Chimban'),
(56, 'Choropampa'),
(56, 'Cochabamba'),
(56, 'Conchán'),
(56, 'Huambos'),
(56, 'Lajas'),
(56, 'Llama'),
(56, 'Miracosta'),
(56, 'Paccha'),
(56, 'Pion'),
(56, 'Querocoto'),
(56, 'San Juan de Licupis'),
(56, 'Tacabamba'),
(56, 'Tocmoche'),
(56, 'Chalamarca'),

-- Provincia: Contumazá
(57, 'Contumazá'),
(57, 'Chilete'),
(57, 'Cupisnique'),
(57, 'Guzmango'),
(57, 'San Benito'),
(57, 'Santa Cruz de Toledo'),
(57, 'Tantarica'),
(57, 'Yonan'),

-- Provincia: Cutervo
(58, 'Cutervo'),
(58, 'Callayuc'),
(58, 'Choros'),
(58, 'Cujillo'),
(58, 'La Ramada'),
(58, 'Pimpingos'),
(58, 'Querocotillo'),
(58, 'San Andrés de Cutervo'),
(58, 'San Juan de Cutervo'),
(58, 'San Luis de Lucma'),
(58, 'Santa Cruz'),
(58, 'Santo Domingo de la Capilla'),
(58, 'Santo Tomás'),
(58, 'Socota'),
(58, 'Toribio Casanova'),

-- Provincia: Hualgayoc
(59, 'Bambamarca'),
(59, 'Chugur'),
(59, 'Hualgayoc'),

-- Provincia: Jaén
(60, 'Jaén'),
(60, 'Bellavista'),
(60, 'Chontali'),
(60, 'Colasay'),
(60, 'Huabal'),
(60, 'Las Pirias'),
(60, 'Pomahuaca'),
(60, 'Pucará'),
(60, 'Sallique'),
(60, 'San Felipe'),
(60, 'San José del Alto'),
(60, 'Santa Rosa'),

-- Provincia: San Ignacio
(61, 'San Ignacio'),
(61, 'Chirinos'),
(61, 'Huarango'),
(61, 'La Coipa'),
(61, 'Namballe'),
(61, 'San José de Lourdes'),
(61, 'Tabaconas'),

-- Provincia: San Marcos
(62, 'Pedro Gálvez'),
(62, 'Chancay'),
(62, 'Eduardo Villanueva'),
(62, 'Gregorio Pita'),
(62, 'Ichocán'),
(62, 'José Manuel Quiroz'),
(62, 'José Sabogal'),

-- Provincia: San Miguel
(63, 'San Miguel'),
(63, 'Bolívar'),
(63, 'Calquis'),
(63, 'Catilluc'),
(63, 'El Prado'),
(63, 'La Florida'),
(63, 'Llapa'),
(63, 'Nanchoc'),
(63, 'Niepos'),
(63, 'San Gregorio'),
(63, 'San Silvestre de Cochan'),
(63, 'Tongod'),
(63, 'Unión Agua Blanca'),

-- Provincia: San Pablo
(64, 'San Pablo'),
(64, 'San Bernardino'),
(64, 'San Luis'),
(64, 'Tumbadén'),

-- Provincia: Santa Cruz
(65, 'Santa Cruz'),
(65, 'Andabamba'),
(65, 'Catache'),
(65, 'Chancaybaños'),
(65, 'La Esperanza'),
(65, 'Ninabamba'),
(65, 'Pulán'),
(65, 'Saucepampa'),
(65, 'Sexi'),
(65, 'Uticyacu'),
(65, 'Yauyucan'),

(66, 'Callao'),
(66, 'Bellavista'),
(66, 'Carmen de la Legua Reynoso'),
(66, 'La Perla'),
(66, 'La Punta'),
(66, 'Ventanilla'),
(66, 'Mi Perú'),

-- Acomayo (idprovincia = 67)
(67, 'Acomayo'),
(67, 'Acopia'),
(67, 'Acos'),
(67, 'Mosoc Llacta'),
(67, 'Pomacanchi'),
(67, 'Rondocan'),
(67, 'Sangarará'),

-- Anta (idprovincia = 68)
(68, 'Anta'),
(68, 'Ancahuasi'),
(68, 'Cachimayo'),
(68, 'Chinchaypujio'),
(68, 'Huarocondo'),
(68, 'Limatambo'),
(68, 'Mollepata'),
(68, 'Pucyura'),
(68, 'Zurite'),

-- Calca (idprovincia = 69)
(69, 'Calca'),
(69, 'Coya'),
(69, 'Lamay'),
(69, 'Lares'),
(69, 'Pisac'),
(69, 'San Salvador'),
(69, 'Taray'),
(69, 'Yanatile'),

-- Canas (idprovincia = 70)
(70, 'Yanaoca'),
(70, 'Checca'),
(70, 'Kunturkanki'),
(70, 'Langui'),
(70, 'Layo'),
(70, 'Pampamarca'),
(70, 'Quehue'),
(70, 'Tupac Amaru'),

-- Canchis (idprovincia = 71)
(71, 'Sicuani'),
(71, 'Checacupe'),
(71, 'Combapata'),
(71, 'Marangani'),
(71, 'Pitumarca'),
(71, 'San Pablo'),
(71, 'San Pedro'),
(71, 'Tinta'),

-- Chumbivilcas (idprovincia = 72)
(72, 'Santo Tomás'),
(72, 'Capacmarca'),
(72, 'Chamaca'),
(72, 'Colquemarca'),
(72, 'Livitaca'),
(72, 'Llusco'),
(72, 'Quiñota'),
(72, 'Velille'),

-- Cusco (idprovincia = 73)
(73, 'Cusco'),
(73, 'Ccorca'),
(73, 'Poroy'),
(73, 'San Jerónimo'),
(73, 'San Sebastián'),
(73, 'Santiago'),
(73, 'Saylla'),
(73, 'Wanchaq'),

-- Espinar (idprovincia = 74)
(74, 'Espinar'),
(74, 'Condoroma'),
(74, 'Coporaque'),
(74, 'Ocoruro'),
(74, 'Pallpata'),
(74, 'Pichigua'),
(74, 'Suyckutambo'),
(74, 'Alto Pichigua'),

-- La Convención (idprovincia = 75)
(75, 'Quillabamba'),
(75, 'Echarati'),
(75, 'Huayopata'),
(75, 'Maranura'),
(75, 'Ocobamba'),
(75, 'Santa Ana'),
(75, 'Santa Teresa'),
(75, 'Vilcabamba'),

-- Paruro (idprovincia = 76)
(76, 'Paruro'),
(76, 'Accha'),
(76, 'Ccapi'),
(76, 'Colcha'),
(76, 'Huanoquite'),
(76, 'Omacha'),
(76, 'Paccaritambo'),
(76, 'Pillpinto'),
(76, 'Yaurisque'),

-- Paucartambo (idprovincia = 77)
(77, 'Paucartambo'),
(77, 'Caicay'),
(77, 'Challabamba'),
(77, 'Colquepata'),
(77, 'Huancarani'),
(77, 'Kosñipata'),

-- Quispicanchi (idprovincia = 78)
(78, 'Urcos'),
(78, 'Andahuaylillas'),
(78, 'Camanti'),
(78, 'Ccarhuayo'),
(78, 'Ccatca'),
(78, 'Cusipata'),
(78, 'Huaro'),
(78, 'Lucre'),
(78, 'Marcapata'),
(78, 'Ocongate'),
(78, 'Oropesa'),
(78, 'Quiquijana'),

-- Urubamba (idprovincia = 79)
(79, 'Urubamba'),
(79, 'Chinchero'),
(79, 'Huayllabamba'),
(79, 'Machupicchu'),
(79, 'Maras'),
(79, 'Ollantaytambo'),
(79, 'Yucay'),

-- Acobamba (idprovincia = 80)
(80, 'Acobamba'),
(80, 'Andabamba'),
(80, 'Anta'),
(80, 'Caja'),
(80, 'Marcas'),
(80, 'Paucara'),
(80, 'Pomacocha'),
(80, 'Rosario'),

-- Angaraes (idprovincia = 81)
(81, 'Lircay'),
(81, 'Anchonga'),
(81, 'Callanmarca'),
(81, 'Ccochaccasa'),
(81, 'Chincho'),
(81, 'Congalla'),
(81, 'Huanca-Huanca'),
(81, 'Huayllay Grande'),
(81, 'Julcamarca'),
(81, 'San Antonio de Antaparco'),
(81, 'Santo Tomas de Pata'),
(81, 'Secclla'),

-- Castrovirreyna (idprovincia = 82)
(82, 'Castrovirreyna'),
(82, 'Arma'),
(82, 'Aurahua'),
(82, 'Capillas'),
(82, 'Chupamarca'),
(82, 'Cocas'),
(82, 'Huachos'),
(82, 'Huamatambo'),
(82, 'Mollepampa'),
(82, 'San Juan'),
(82, 'Santa Ana'),
(82, 'Tantara'),
(82, 'Ticrapo'),

-- Churcampa (idprovincia = 83)
(83, 'Churcampa'),
(83, 'Anco'),
(83, 'Chinchihuasi'),
(83, 'El Carmen'),
(83, 'La Merced'),
(83, 'Locroja'),
(83, 'Paucarbamba'),
(83, 'San Miguel de Mayocc'),
(83, 'San Pedro de Coris'),
(83, 'Pachamarca'),
(83, 'Cosme'),

-- Huancavelica (idprovincia = 84)
(84, 'Huancavelica'),
(84, 'Acobambilla'),
(84, 'Acoria'),
(84, 'Conayca'),
(84, 'Cuenca'),
(84, 'Huachocolpa'),
(84, 'Huayllahuara'),
(84, 'Izcuchaca'),
(84, 'Laria'),
(84, 'Manta'),
(84, 'Mariscal Cáceres'),
(84, 'Moya'),
(84, 'Nuevo Occoro'),
(84, 'Palca'),
(84, 'Pilchaca'),
(84, 'Vilca'),
(84, 'Yauli'),
(84, 'Ascensión'),

-- Huaytará (idprovincia = 85)
(85, 'Huaytará'),
(85, 'Ayaví'),
(85, 'Córdova'),
(85, 'Huayacundo Arma'),
(85, 'Laramarca'),
(85, 'Ocoyo'),
(85, 'Pilpichaca'),
(85, 'Querco'),
(85, 'Quito-Arma'),
(85, 'San Antonio de Cusicancha'),
(85, 'San Francisco de Sangayaico'),
(85, 'San Isidro'),
(85, 'Santiago de Chocorvos'),
(85, 'Santiago de Quirahuara'),
(85, 'Santo Domingo de Capillas'),
(85, 'Tambo'),

-- Tayacaja (idprovincia = 86)
(86, 'Pampas'),
(86, 'Acostambo'),
(86, 'Acraquia'),
(86, 'Ahuaycha'),
(86, 'Colcabamba'),
(86, 'Daniel Hernández'),
(86, 'Huachocolpa'),
(86, 'Huaribamba'),
(86, 'Ñahuimpuquio'),
(86, 'Pazos'),
(86, 'Quishuar'),
(86, 'Salcabamba'),
(86, 'Salcahuasi'),
(86, 'San Marcos de Rocchac'),
(86, 'Surcubamba'),
(86, 'Tintay Puncu'),
(86, 'Quichuas'),
(86, 'Andaymarca'),
(86, 'Roble'),
(86, 'Santiago de Tucuma'),

-- Ambo
(87, 'Ambo'),
(87, 'Cayna'),
(87, 'Colpas'),
(87, 'Conchamarca'),
(87, 'Huacar'),
(87, 'San Francisco'),
(87, 'San Rafael'),
(87, 'Tomay Kichwa'),

-- Dos de Mayo
(88, 'La Unión'),
(88, 'Chuquis'),
(88, 'Marías'),
(88, 'Pachas'),
(88, 'Quivilla'),
(88, 'Ripan'),
(88, 'Shunqui'),
(88, 'Sillapata'),
(88, 'Yanas'),

-- Huacaybamba
(89, 'Huacaybamba'),
(89, 'Canchabamba'),
(89, 'Cochabamba'),
(89, 'Pinra'),

-- Huamalíes
(90, 'Llata'),
(90, 'Arancay'),
(90, 'Chavín de Pariarca'),
(90, 'Jacas Grande'),
(90, 'Jircan'),
(90, 'Miraflores'),
(90, 'Monzón'),
(90, 'Punchao'),
(90, 'Puños'),
(90, 'Singa'),
(90, 'Tantamayo'),

-- Huánuco
(91, 'Huánuco'),
(91, 'Amarilis'),
(91, 'Chinchao'),
(91, 'Churubamba'),
(91, 'Margos'),
(91, 'Quisqui (Kichki)'),
(91, 'San Francisco de Cayrán'),
(91, 'San Pedro de Chaulán'),
(91, 'Santa María del Valle'),
(91, 'Yarumayo'),
(91, 'Pillco Marca'),

-- Lauricocha
(92, 'Jesús'),
(92, 'Baños'),
(92, 'Jivia'),
(92, 'Queropalca'),
(92, 'Rondos'),
(92, 'San Francisco de Asís'),
(92, 'San Miguel de Cauri'),

-- Leoncio Prado
(93, 'Rupa Rupa'),
(93, 'Daniel Alomía Robles'),
(93, 'Hermílio Valdizán'),
(93, 'José Crespo y Castillo'),
(93, 'Luyando'),
(93, 'Mariano Dámaso Beraún'),

-- Marañón
(94, 'Huacrachuco'),
(94, 'Cholon'),
(94, 'San Buenaventura'),

-- Pachitea
(95, 'Panao'),
(95, 'Chaglla'),
(95, 'Molino'),
(95, 'Umari'),

-- Puerto Inca
(96, 'Puerto Inca'),
(96, 'Codo del Pozuzo'),
(96, 'Honoria'),
(96, 'Tournavista'),
(96, 'Yuyapichis'),

-- Yarowilca
(97, 'Chavinillo'),
(97, 'Cahuac'),
(97, 'Chacabamba'),
(97, 'Aparicio Pomares'),
(97, 'Jacas Chico'),
(97, 'Obas'),
(97, 'Pampamarca'),
(97, 'Choras'),

-- Chincha
(98, 'Alto Larán'),
(98, 'Chincha Alta'),
(98, 'Chincha Baja'),
(98, 'El Carmen'),
(98, 'Grocio Prado'),
(98, 'Pueblo Nuevo'),
(98, 'San Juan de Yanac'),
(98, 'San Pedro de Huacarpana'),
(98, 'Sunampe'),
(98, 'Tambo de Mora'),
-- Ica
(99, 'Ica'),
(99, 'La Tinguiña'),
(99, 'Los Aquijes'),
(99, 'Ocucaje'),
(99, 'Pachacútec'),
(99, 'Parcona'),
(99, 'Pueblo Nuevo'),
(99, 'Salas'),
(99, 'San José de los Molinos'),
(99, 'San Juan Bautista'),
(99, 'Santiago'),
(99, 'Tate'),
(99, 'Yauca del Rosario'),
-- Nazca
(100, 'Changuillo'),
(100, 'El Ingenio'),
(100, 'Marcona'),
(100, 'Nazca'),
(100, 'Vista Alegre'),
-- Palpa
(11, 'Llipata'),
(11, 'Palpa'),
(11, 'Río Grande'),
(11, 'Santa Cruz'),
(11, 'Tibillo'),
-- Pisco
(11, 'Huancano'),
(11, 'Humay'),
(11, 'Independencia'),
(11, 'Paracas'),
(11, 'Pisco'),
(11, 'San Andrés'),
(11, 'San Clemente'),
(11, 'Túpac Amaru Inca'),

-- Chanchamayo
(12, 'Chanchamayo'),
(12, 'Perene'),
(12, 'Pichanaqui'),
(12, 'San Luis de Shuaro'),
(12, 'San Ramón'),
(12, 'Vitoc'),
-- Chupaca
(12, 'Ahuac'),
(12, 'Chongos Bajo'),
(12, 'Chupaca'),
(12, 'Huachac'),
(12, 'Huamancaca Chico'),
(12, 'San Juan de Iscos'),
(12, 'San Juan de Jarpa'),
(12, 'Tres de Diciembre'),
(12, 'Yanacancha'),
-- Concepción
(12, 'Aco'),
(12, 'Andamarca'),
(12, 'Chambara'),
(12, 'Cochas'),
(12, 'Comas'),
(12, 'Concepción'),
(12, 'Heroínas Toledo'),
(12, 'Manzanares'),
(12, 'Mariscal Castilla'),
(12, 'Matahuasi'),
(12, 'Mito'),
(12, 'Nueve de Julio'),
(12, 'Orcotuna'),
(12, 'San José de Quero'),
(12, 'Santa Rosa de Ocopa'),
-- Huancayo
(12, 'Carhuacallanga'),
(12, 'Chacapampa'),
(12, 'Chicche'),
(12, 'Chilca'),
(12, 'Chongos Alto'),
(12, 'Chupuro'),
(12, 'Colca'),
(12, 'Cullhuas'),
(12, 'El Tambo'),
(12, 'Huancayo'),
(12, 'Huacrapuquio'),
(12, 'Hualhuas'),
(12, 'Huancan'),
(12, 'Huasicancha'),
(12, 'Huayucachi'),
(12, 'Ingenio'),
(12, 'Pariahuanca'),
(12, 'Pilcomayo'),
(12, 'Pucara'),
(12, 'Quichuay'),
(12, 'Quilcas'),
(12, 'San Agustín'),
(12, 'San Jerónimo de Tunán'),
(12, 'Santo Domingo de Acobamba'),
(12, 'Sapallanga'),
(12, 'Sicaya'),
(12, 'Viques'),
-- Jauja
(12, 'Acolla'),
(12, 'Apata'),
(12, 'Ataura'),
(12, 'Canchayllo'),
(12, 'Curicaca'),
(12, 'El Mantaro'),
(12, 'Huamali'),
(12, 'Huaripampa'),
(12, 'Huertas'),
(12, 'Janjaillo'),
(12, 'Jauja'),
(12, 'Julcán'),
(12, 'Leonor Ordóñez'),
(12, 'Llocllapampa'),
(12, 'Marco'),
(12, 'Masma'),
(12, 'Masma Chicche'),
(12, 'Molinos'),
(12, 'Monobamba'),
(12, 'Muqui'),
(12, 'Muquiyauyo'),
(12, 'Paca'),
(12, 'Paccha'),
(12, 'Pancan'),
(12, 'Parco'),
(12, 'Pomacancha'),
(12, 'Ricran'),
(12, 'San Lorenzo'),
(12, 'San Pedro de Chunan'),
(12, 'Sincos'),
(12, 'Tunanmarca'),
(12, 'Yauli'),
(12, 'Yauyos'),

-- Junín
(12, 'Carhuamayo'),
(12, 'Junín'),
(12, 'Ondores'),
(12, 'Ulcumayo'),
-- Satipo
(12, 'Coviriali'),
(12, 'Llaylla'),
(12, 'Mazamari'),
(12, 'Pampa Hermosa'),
(12, 'Pangoa'),
(12, 'Río Negro'),
(12, 'Río Tambo'),
(12, 'Satipo'),
-- Tarma
(12, 'Acobamba'),
(12, 'Huaricolca'),
(12, 'Huasahuasi'),
(12, 'La Unión'),
(12, 'Palca'),
(12, 'Palcamayo'),
(12, 'San Pedro de Cajas'),
(12, 'Tarma'),
-- Yauli
(12, 'Huay-Huay'),
(12, 'La Oroya'),
(12, 'Marcapomacocha'),
(12, 'Morococha'),
(12, 'Paccha'),
(12, 'Santa Bárbara de Carhuacayan'),
(12, 'Santa Rosa de Sacco'),
(12, 'Suitucancha'),
(12, 'Yauli'),

-- Ascope
(13, 'Ascope'),
(13, 'Chicama'),
(13, 'Chocope'),
(13, 'Magdalena de Cao'),
(13, 'Paiján'),
(13, 'Rázuri'),
(13, 'Santiago de Cao'),
(13, 'Casa Grande'),
-- Bolívar
(13, 'Bolívar'),
(13, 'Bambamarca'),
(13, 'Condormarca'),
(13, 'Longotea'),
(13, 'Uchumarca'),
(13, 'Ucuncha'),
-- Chepén
(13, 'Chepén'),
(13, 'Pacanga'),
(13, 'Pueblo Nuevo'),
-- Gran Chimú
(13, 'Cascas'),
(13, 'Lucma'),
(13, 'Marmot'),
(13, 'Sayapullo'),
-- Julcán
(13, 'Julcán'),
(13, 'Calamarca'),
(13, 'Carabamba'),
(13, 'Huaso'),
-- Otuzco
(13, 'Otuzco'),
(13, 'Agallpampa'),
(13, 'Charat'),
(13, 'Huaranchal'),
(13, 'La Cuesta'),
(13, 'Mache'),
(13, 'Paranday'),
(13, 'Salpo'),
(13, 'Sinsicap'),
(13, 'Usquil'),
-- Pacasmayo
(13, 'San Pedro de Lloc'),
(13, 'Guadalupe'),
(13, 'Jequetepeque'),
(13, 'Pacasmayo'),
(13, 'San José'),
-- Pataz
(13, 'Tayabamba'),
(13, 'Buldibuyo'),
(13, 'Chillia'),
(13, 'Huancaspata'),
(13, 'Huaylillas'),
(13, 'Huayo'),
(13, 'Ongón'),
(13, 'Parcoy'),
(13, 'Pataz'),
(13, 'Pías'),
(13, 'Santiago de Challas'),
(13, 'Taurija'),
(13, 'Urpay'),
-- Sánchez Carrión
(13, 'Huamachuco'),
(13, 'Chugay'),
(13, 'Cochorco'),
(13, 'Curgos'),
(13, 'Marcabal'),
(13, 'Sanagorán'),
(13, 'Sarin'),
(13, 'Sartimbamba'),
-- Santiago de Chuco
(13, 'Santiago de Chuco'),
(13, 'Angasmarca'),
(13, 'Cachicadán'),
(13, 'Mollebamba'),
(13, 'Mollepata'),
(13, 'Quiruvilca'),
(13, 'Santa Cruz de Chuca'),
(13, 'Sitabamba'),
-- Trujillo
(13, 'Trujillo'),
(13, 'El Porvenir'),
(13, 'Florencia de Mora'),
(13, 'Huanchaco'),
(13, 'La Esperanza'),
(13, 'Laredo'),
(13, 'Moche'),
(13, 'Poroto'),
(13, 'Salaverry'),
(13, 'Simbal'),
(13, 'Víctor Larco Herrera'),
-- Virú
(13, 'Virú'),
(13, 'Chao'),
(13, 'Guadalupito'),

-- Chiclayo
(14, 'Chiclayo'),
(14, 'Chongoyape'),
(14, 'Eten'),
(14, 'Eten Puerto'),
(14, 'José Leonardo Ortiz'),
(14, 'La Victoria'),
(14, 'Lagunas'),
(14, 'Monsefú'),
(14, 'Nueva Arica'),
(14, 'Oyotún'),
(14, 'Patapo'),
(14, 'Picsi'),
(14, 'Pimentel'),
(14, 'Pomalca'),
(14, 'Pucalá'),
(14, 'Reque'),
(14, 'Santa Rosa'),
(14, 'Saña'),
(14, 'Tuman'),
-- Ferreñafe
(14, 'Cañaris'),
(14, 'Ferreñafe'),
(14, 'Incahuasi'),
(14, 'Manuel Antonio Mesones Muro'),
(14, 'Pitipo'),
(14, 'Pueblo Nuevo'),
-- Lambayeque
(14, 'Chochope'),
(14, 'Illimo'),
(14, 'Jayanca'),
(14, 'Lambayeque'),
(14, 'Mochumí'),
(14, 'Morrope'),
(14, 'Motupe'),
(14, 'Olmos'),
(14, 'Pacora'),
(14, 'Salas'),
(14, 'San José'),
(14, 'Túcume'),

-- Barranca
(15, 'Barranca'),
(15, 'Paramonga'),
(15, 'Pativilca'),
(15, 'Supe'),
(15, 'Supe Puerto'),
-- Cajatambo
(15, 'Cajatambo'),
(15, 'Copa'),
(15, 'Gorgor'),
(15, 'Huancapon'),
(15, 'Manas'),
-- Canta
(15, 'Arahuay'),
(15, 'Canta'),
(15, 'Huamantanga'),
(15, 'Huaros'),
(15, 'Lachaqui'),
(15, 'San Buenaventura'),
(15, 'Santa Rosa de Quives'),
-- Cañete
(15, 'Asia'),
(15, 'Calango'),
(15, 'Cerro Azul'),
(15, 'Chilca'),
(15, 'Coayllo'),
(15, 'Imperial'),
(15, 'Lunahuana'),
(15, 'Mala'),
(15, 'Nuevo Imperial'),
(15, 'Pacaran'),
(15, 'Quilmana'),
(15, 'San Antonio'),
(15, 'San Luis'),
(15, 'Santa Cruz de Flores'),
(15, 'Zuniga'),
-- Huaral
(15, 'Atavillos Alto'),
(15, 'Atavillos Bajo'),
(15, 'Aucallama'),
(15, 'Chancay'),
(15, 'Huaral'),
(15, 'Ihuari'),
(15, 'Lampian'),
(15, 'Pacaraos'),
(15, 'San Miguel de Acos'),
(15, 'Santa Cruz de Andamarca'),
(15, 'Sumbilca'),
(15, 'Veintisiete de Noviembre'),
-- Huarochirí
(15, 'Antioquia'),
(15, 'Callahuanca'),
(15, 'Carampoma'),
(15, 'Chicla'),
(15, 'Cuenca'),
(15, 'Huachupampa'),
(15, 'Huanza'),
(15, 'Huarochiri'),
(15, 'Lahuaytambo'),
(15, 'Langa'),
(15, 'Laraos'),
(15, 'Mariatana'),
(15, 'Matucana'),
(15, 'Ricardo Palma'),
(15, 'San Andrés de Tupicocha'),
(15, 'San Antonio'),
(15, 'San Bartolome'),
(15, 'San Damian'),
(15, 'San Juan de Iris'),
(15, 'San Juan de Tantaranche'),
(15, 'San Lorenzo de Quinti'),
(15, 'San Mateo'),
(15, 'San Mateo de Otao'),
(15, 'San Pedro de Casta'),
(15, 'San Pedro de Huancayre'),
(15, 'Sangallaya'),
(15, 'Santa Cruz de Cocachacra'),
(15, 'Santa Eulalia'),
(15, 'Santiago de Anchucaya'),
(15, 'Santiago de Tuna'),
(15, 'Santo Domingo de los Olleros'),
(15, 'Surco'),
-- Huaura
(15, 'Ambar'),
(15, 'Caleta de Carquin'),
(15, 'Checras'),
(15, 'Hualmay'),
(15, 'Huaura'),
(15, 'Leoncio Prado'),
(15, 'Paccho'),
(15, 'Santa Leonor'),
(15, 'Santa Maria'),
(15, 'Sayan'),
(15, 'Vegueta'),
-- Lima
(15, 'Ancón'),
(15, 'Ate'),
(15, 'Barranco'),
(15, 'Breña'),
(15, 'Carabayllo'),
(15, 'Chaclacayo'),
(15, 'Chorrillos'),
(15, 'Cieneguilla'),
(15, 'Comas'),
(15, 'El Agustino'),
(15, 'Independencia'),
(15, 'Jesús María'),
(15, 'La Molina'),
(15, 'La Victoria'),
(15, 'Lima'),
(15, 'Lince'),
(15, 'Los Olivos'),
(15, 'Lurigancho'),
(15, 'Lurín'),
(15, 'Magdalena del Mar'),
(15, 'Miraflores'),
(15, 'Pachacamac'),
(15, 'Pucusana'),
(15, 'Pueblo Libre'),
(15, 'Puente Piedra'),
(15, 'Punta Hermosa'),
(15, 'Punta Negra'),
(15, 'Rímac'),
(15, 'San Bartolo'),
(15, 'San Borja'),
(15, 'San Isidro'),
(15, 'San Juan de Lurigancho'),
(15, 'San Juan de Miraflores'),
(15, 'San Luis'),
(15, 'San Martín de Porres'),
(15, 'San Miguel'),
(15, 'Santa Anita'),
(15, 'Santa María del Mar'),
(15, 'Santa Rosa'),
(15, 'Santiago de Surco'),
(15, 'Surquillo'),
(15, 'Villa El Salvador'),
(15, 'Villa María del Triunfo'),
-- Oyón
(15, 'Andajes'),
(15, 'Caujul'),
(15, 'Cochamarca'),
(15, 'Navan'),
(15, 'Oyón'),
(15, 'Pachangara'),
-- Yauyos
(15, 'Alis'),
(15, 'Allauca'),
(15, 'Ayaviri'),
(15, 'Azángaro'),
(15, 'Cacra'),
(15, 'Carania'),
(15, 'Catahuasi'),
(15, 'Chocos'),
(15, 'Cochas'),
(15, 'Colonia'),
(15, 'Hongos'),
(15, 'Huampara'),
(15, 'Huancaya'),
(15, 'Huangascar'),
(15, 'Huantán'),
(15, 'Huañec'),
(15, 'Laraos'),
(15, 'Lincha'),
(15, 'Madean'),
(15, 'Miraflores'),
(15, 'Omas'),
(15, 'Putinza'),
(15, 'Quinches'),
(15, 'Quinocay'),
(15, 'San Joaquín'),
(15, 'San Pedro de Pilas'),
(15, 'Tanta'),
(15, 'Tauripampa'),
(15, 'Tomas'),
(15, 'Tupe'),
(15, 'Viñac'),
(15, 'Vitis'),

-- Alto Amazonas
(16, 'Balsapuerto'),
(16, 'Jeberos'),
(16, 'Lagunas'),
(16, 'Santa Cruz'),
(16, 'Teniente Cesar López Rojas'),
(16, 'Yurimaguas'),
-- Datem del Marañón
(16, 'Andoas'),
(16, 'Barranca'),
(16, 'Cahuapanas'),
(16, 'Manseriche'),
(16, 'Morona'),
(16, 'Pastaza'),
-- Loreto
(16, 'Nauta'),
(16, 'Parinari'),
(16, 'Tigre'),
(16, 'Trompeteros'),
(16, 'Urarinas'),
-- Mariscal Ramón Castilla
(16, 'Pebas'),
(16, 'Ramón Castilla'),
(16, 'San Pablo'),
(16, 'Yavarí'),
-- Maynas
(16, 'Alto Nanay'),
(16, 'Fernando Lores'),
(16, 'Indiana'),
(16, 'Iquitos'),
(16, 'Las Amazonas'),
(16, 'Mazan'),
(16, 'Napo'),
(16, 'Punchana'),
(16, 'Torres Causana'),
(16, 'Belén'),
(16, 'San Juan Bautista'),
-- Putumayo
(16, 'Putumayo'),
(16, 'Rosa Panduro'),
(16, 'Teniente Manuel Clavero'),
(16, 'Yaguas'),
-- Requena
(16, 'Alto Tapiche'),
(16, 'Capelo'),
(16, 'Emilio San Martín'),
(16, 'Jenaro Herrera'),
(16, 'Maquia'),
(16, 'Puinahua'),
(16, 'Requena'),
(16, 'Saquena'),
(16, 'Soplin'),
(16, 'Tapiche'),
(16, 'Yaquerana'),
-- Ucayali
(16, 'Contamana'),
(16, 'Inahuaya'),
(16, 'Padre Márquez'),
(16, 'Pampa Hermosa'),
(16, 'Sarayacu'),
(16, 'Vargas Guerra'),

-- Manu
(17, 'Fitzcarrald'),
(17, 'Madre de Dios'),
(17, 'Manu'),
(17, 'Huepetuhe'),
-- Tahuamanu
(17, 'Iñapari'),
(17, 'Iberia'),
(17, 'Tahuamanu'),
-- Tambopata
(17, 'Inambari'),
(17, 'Las Piedras'),
(17, 'Laberinto'),
(17, 'Tambopata'),

-- General Sánchez Cerro
(18, 'Chojata'),
(18, 'Coalaque'),
(18, 'Ichuña'),
(18, 'La Capilla'),
(18, 'Lloque'),
(18, 'Matalaque'),
(18, 'Omate'),
(18, 'Puquina'),
(18, 'Quinistaquillas'),
(18, 'Ubinas'),
(18, 'Yunga'),
-- Ilo
(18, 'El Algarrobal'),
(18, 'Ilo'),
(18, 'Pacocha'),
-- Mariscal Nieto
(18, 'Carumas'),
(18, 'Cuchumbaya'),
(18, 'Moquegua'),
(18, 'Samegua'),
(18, 'San Cristóbal'),
(18, 'Torata'),

-- Daniel Alcides Carrión
(19, 'Chacayan'),
(19, 'Goyllarisquizga'),
(19, 'Paucar'),
(19, 'San Pedro de Pillao'),
(19, 'Santa Ana de Tusi'),
(19, 'Tapuc'),
(19, 'Vilcabamba'),
(19, 'Yanahuanca'),
-- Oxapampa
(19, 'Chontabamba'),
(19, 'Constitución'),
(19, 'Huancabamba'),
(19, 'Oxapampa'),
(19, 'Palcazu'),
(19, 'Pozuzo'),
(19, 'Puerto Bermúdez'),
(19, 'Villa Rica'),
-- Pasco
(19, 'Chaupimarca'),
(19, 'Huachon'),
(19, 'Huariaca'),
(19, 'Huayllay'),
(19, 'Ninacaca'),
(19, 'Pallanchacra'),
(19, 'Paucartambo'),
(19, 'San Francisco de Asís de Yarusyacán'),
(19, 'Simón Bolívar'),
(19, 'Ticlacayán'),
(19, 'Tinyahuarco'),
(19, 'Vicco'),
(19, 'Yanacancha'),

-- Ayabaca
(20, 'Ayabaca'),
(20, 'Frias'),
(20, 'Jilili'),
(20, 'Lagunas'),
(20, 'Montero'),
(20, 'Pacaipampa'),
(20, 'Paimas'),
(20, 'Sapillica'),
(20, 'Sicchez'),
(20, 'Suyo'),
-- Huancabamba
(20, 'Canchaque'),
(20, 'El Carmen de la Frontera'),
(20, 'Huancabamba'),
(20, 'Huarmaca'),
(20, 'Lalaquiz'),
(20, 'San Miguel de El Faique'),
(20, 'Sondor'),
(20, 'Sondorillo'),
-- Morropón
(20, 'Buenos Aires'),
(20, 'Chalaco'),
(20, 'Chulucanas'),
(20, 'La Matanza'),
(20, 'Morropon'),
(20, 'Salitral'),
(20, 'San Juan de Bigote'),
(20, 'Santa Catalina de Mossa'),
(20, 'Santo Domingo'),
(20, 'Yamango'),
-- Paita
(20, 'Amotape'),
(20, 'Arenal'),
(20, 'Colan'),
(20, 'La Huaca'),
(20, 'Paita'),
(20, 'Tamarindo'),
(20, 'Vichayal'),
-- Piura
(20, 'Castilla'),
(20, 'Catacaos'),
(20, 'Cura Mori'),
(20, 'El Tallan'),
(20, 'La Arena'),
(20, 'La Union'),
(20, 'Las Lomas'),
(20, 'Piura'),
(20, 'Tambo Grande'),
-- Sechura
(20, 'Bellavista de la Union'),
(20, 'Bernal'),
(20, 'Cristo Nos Valga'),
(20, 'Rinconada Llicuar'),
(20, 'Sechura'),
(20, 'Vice'),
-- Sullana
(20, 'Bellavista'),
(20, 'Ignacio Escudero'),
(20, 'Lancones'),
(20, 'Marcavelica'),
(20, 'Miguel Checa'),
(20, 'Querecotillo'),
(20, 'Salitral'),
(20, 'Sullana'),
-- Talara
(20, 'El Alto'),
(20, 'La Brea'),
(20, 'Lobitos'),
(20, 'Los Organos'),
(20, 'Mancora'),
(20, 'Parinas'),


(21, 'Azángaro'),
(21, 'Achaya'),
(21, 'Arapa'),
(21, 'Asillo'),
(21, 'Caminaca'),
(21, 'Chupa'),
(21, 'José Domingo Choquehuanca'),
(21, 'Muñani'),
(21, 'Potoni'),
(21, 'Samán'),
(21, 'San Antón'),
(21, 'San José'),
(21, 'San Juan de Salinas'),
(21, 'Santiago de Pupuja'),
(21, 'Tirapata'),

(21, 'Carabaya'),
(21, 'Ajoyani'),
(21, 'Ayapata'),
(21, 'Coasa'),
(21, 'Corani'),
(21, 'Crucero'),
(21, 'Ituata'),
(21, 'Macusani'),
(21, 'Ollachea'),
(21, 'San Gabán'),
(21, 'Usicayos'),

(21, 'Chucuito'),
(21, 'Desaguadero'),
(21, 'Huacullani'),
(21, 'Juli'),
(21, 'Kelluyo'),
(21, 'Pisacoma'),
(21, 'Pomata'),
(21, 'Zepita'),

(21, 'El Collao'),
(21, 'Capaso'),
(21, 'Conduriri'),
(21, 'Ilave'),
(21, 'Pilcuyo'),
(21, 'Santa Rosa'),

(21, 'Huancané'),
(21, 'Cojata'),
(21, 'Huancané'),
(21, 'Huatasani'),
(21, 'Inchupalla'),
(21, 'Pusi'),
(21, 'Rosaspata'),
(21, 'Taraco'),
(21, 'Vilque Chico'),

(21, 'Lampa'),
(21, 'Cabanilla'),
(21, 'Calapuja'),
(21, 'Lampa'),
(21, 'Nicasio'),
(21, 'Ocuviri'),
(21, 'Palca'),
(21, 'Paratía'),
(21, 'Pucará'),
(21, 'Santa Lucía'),
(21, 'Vilavila'),

(21, 'Melgar'),
(21, 'Antauta'),
(21, 'Ayaviri'),
(21, 'Cupi'),
(21, 'Llalli'),
(21, 'Macari'),
(21, 'Nuñoa'),
(21, 'Orurillo'),
(21, 'Santa Rosa'),
(21, 'Umachiri'),

(21, 'Moho'),
(21, 'Conima'),
(21, 'Huayrapata'),
(21, 'Moho'),
(21, 'Tilali'),

(21, 'Puno'),
(21, 'Acora'),
(21, 'Amantani'),
(21, 'Atuncolla'),
(21, 'Capachica'),
(21, 'Chucuito'),
(21, 'Coata'),
(21, 'Huata'),
(21, 'Mañazo'),
(21, 'Paucarcolla'),
(21, 'Pichacani'),
(21, 'Platería'),
(21, 'Puno'),
(21, 'San Antonio'),
(21, 'Tiquillaca'),
(21, 'Vilque'),

(21, 'San Antonio de Putina'),
(21, 'Ananea'),
(21, 'Pedro Vilca Apaza'),
(21, 'Putina'),
(21, 'Quilcapuncu'),
(21, 'Sina'),

(21, 'San Román'),
(21, 'Cabana'),
(21, 'Cabanillas'),
(21, 'Caracoto'),
(21, 'Juliaca'),

(21, 'Sandia'),
(21, 'Alto Inambari'),
(21, 'Cuyocuyo'),
(21, 'Limbani'),
(21, 'Patambuco'),
(21, 'Phara'),
(21, 'Quiaca'),
(21, 'San Juan del Oro'),
(21, 'San Pedro de Putina Punco'),
(21, 'Sandia'),
(21, 'Yanahuaya'),

(21, 'Yunguyo'),
(21, 'Anapia'),
(21, 'Copani'),
(21, 'Cuturapi'),
(21, 'Ollaraya'),
(21, 'Tinicachi'),
(21, 'Unicachi');

-- Bellavista
INSERT INTO distritos (idprovincia, nombre) VALUES
(22, 'Alto Biavo'),
(22, 'Bajo Biavo'),
(22, 'Bellavista'),
(22, 'Huallaga'),
(22, 'San Pablo'),
(22, 'San Rafael');

-- El Dorado
INSERT INTO distritos (idprovincia, nombre) VALUES
(22, 'Agua Blanca'),
(22, 'San José de Sisa'),
(22, 'San Martín'),
(22, 'Santa Rosa'),
(22, 'Shatoja');

-- Huallaga
INSERT INTO distritos (idprovincia, nombre) VALUES
(22, 'Alto Saposoa'),
(22, 'El Eslabón'),
(22, 'Piscoyacu'),
(22, 'Sacanche'),
(22, 'Saposoa'),
(22, 'Tingo de Saposoa');

-- Lamas
INSERT INTO distritos (idprovincia, nombre) VALUES
(22, 'Alonso de Alvarado'),
(22, 'Barranquita'),
(22, 'Caynarachi'),
(22, 'Cuñumbuqui'),
(22, 'Lamas'),
(22, 'Pinto Recodo'),
(22, 'Rumisapa'),
(22, 'San Roque de Cumbaza'),
(22, 'Shanao'),
(22, 'Tabalosos'),
(22, 'Zapatero');

-- Mariscal Cáceres
INSERT INTO distritos (idprovincia, nombre) VALUES
(22, 'Campanilla'),
(22, 'Huicungo'),
(22, 'Juanjuí'),
(22, 'Pachiza'),
(22, 'Pajarillo');

-- Moyobamba
INSERT INTO distritos (idprovincia, nombre) VALUES
(22, 'Calzada'),
(22, 'Habana'),
(22, 'Jepelacio'),
(22, 'Moyobamba'),
(22, 'Soritor'),
(22, 'Yantalo');

-- Picota
INSERT INTO distritos (idprovincia, nombre) VALUES
(22, 'Buenos Aires'),
(22, 'Caspisapa'),
(22, 'Picota'),
(22, 'Pilluana'),
(22, 'Pucacaca'),
(22, 'San Cristóbal'),
(22, 'San Hilarión'),
(22, 'Shamboyacu'),
(22, 'Tingo de Ponasa'),
(22, 'Tres Unidos');

-- Rioja
INSERT INTO distritos (idprovincia, nombre) VALUES
(22, 'Awajun'),
(22, 'Elias Soplin Vargas'),
(22, 'Nueva Cajamarca'),
(22, 'Pardo Miguel'),
(22, 'Posic'),
(22, 'Rioja'),
(22, 'San Fernando'),
(22, 'Yorongos'),
(22, 'Yuracyacu');

-- San Martín
INSERT INTO distritos (idprovincia, nombre) VALUES
(22, 'Alberto Leveau'),
(22, 'Cacatachi'),
(22, 'Chazuta'),
(22, 'Chipurana'),
(22, 'El Porvenir'),
(22, 'Huimbayoc'),
(22, 'Juan Guerra'),
(22, 'La Banda de Shilcayo'),
(22, 'Morales'),
(22, 'Papaplaya'),
(22, 'San Antonio'),
(22, 'Sauce'),
(22, 'Shapaja'),
(22, 'Tarapoto');

-- Tocache
INSERT INTO distritos (idprovincia, nombre) VALUES
(22, 'Nuevo Progreso'),
(22, 'Polvora'),
(22, 'Shunte'),
(22, 'Tocache'),
(22, 'Uchiza'),

-- Provincia: Candarave
(23, 'Cairani'),
(23, 'Camilaca'),
(23, 'Candarave'),
(23, 'Curibaya'),
(23, 'Huanuara'),
(23, 'Quilahuani'),

-- Provincia: Jorge Basadre
(23, 'Ilabaya'),
(23, 'Ite'),
(23, 'Locumba'),

-- Provincia: Tacna
(23, 'Alto de la Alianza'),
(23, 'Calana'),
(23, 'Ciudad Nueva'),
(23, 'Inclán'),
(23, 'Pachía'),
(23, 'Palca'),
(23, 'Pocollay'),
(23, 'Sama'),
(23, 'Tacna'),
(23, 'Coronel Gregorio Albarracín Lanchipa'),

-- Provincia: Tarata
(23, 'Estique'),
(23, 'Estique-Pampa'),
(23, 'Sitajara'),
(23, 'Susapaya'),
(23, 'Tarata'),
(23, 'Tarucachi'),
(23, 'Ticaco'),

-- Provincia: Contralmirante Villar
(24, 'Canoas de Punta Sal'),
(24, 'Casitas'),
(24, 'Zorritos'),

-- Provincia: Tumbes
(24, 'Corrales'),
(24, 'La Cruz'),
(24, 'Pampas de Hospital'),
(24, 'San Jacinto'),
(24, 'San Juan de la Virgen'),
(24, 'Tumbes'),

-- Provincia: Zarumilla
(24, 'Aguas Verdes'),
(24, 'Matapalo'),
(24, 'Papayal'),
(24, 'Zarumilla'),


-- Provincia: Atalaya
(25, 'Raymondi'),
(25, 'Sepahua'),
(25, 'Tahuanía'),
(25, 'Yurúa'),

-- Provincia: Coronel Portillo
(25, 'Callería'),
(25, 'Campoverde'),
(25, 'Iparía'),
(25, 'Masisea'),
(25, 'Yarinacocha'),
(25, 'Nueva Requena'),
(25, 'Manantay'),

-- Provincia: Padre Abad
(25, 'Padre Abad'),
(25, 'Irazola'),
(25, 'Curimaná'),

-- Provincia: Purús
(25, 'Purús');